import images from www.netz39.de
penguineer/cdn.netz39.de pull request #4
Opened 2024-11-05 19:52 UTC by teuserer

Ich habe die Dateipfade unter `assets/img/` aus dem www.netz39.de repo genommen und dann diese Dateien von der Webseite heruntergeladen.
Zwei Bilder konnte ich nicht hinzufügen, weil sie ungültig sind:
https://www.netz39.de/assets/img/post-img/2012/IMG_20121122_200631.jpg
und
https://www.netz39.de/assets/img/post-img/2014/3373_8a9e_500.gif

2024-11-06 08:45 UTC, penguineer commented
Das ist ein sehr gemischter PR. Ich habe  den ersten Commit in #5 übernommen. 
@teuserer kannst Du bitte mal rebasen?

Das wäre hier auch die Stelle, um für future us kurz zu beschreiben, wie die Bilder hier rein gekommen sind. (Im Discord hattest Du das ja gemacht)

2024-11-06 08:49 UTC, penguineer requested changes
Das ist ein sehr gemischter PR. Ich habe den ersten Commit in https://github.com/penguineer/cdn.netz39.de/pull/5 übernommen.
@teuserer kannst Du bitte mal rebasen?

Das wäre hier auch die Stelle, um für future us kurz zu beschreiben, wie die Bilder hier rein gekommen sind. (Im Discord hattest Du das ja gemacht)

2024-11-07 20:47 UTC, teuserer commented
Ich habe die Dateipfade unter `assets/img/` aus dem www.netz39.de repo genommen und dann diese Dateien von der Webseite heruntergeladen.
Zwei Bilder konnte ich nicht hinzufügen, weil sie ungültig sind:
https://www.netz39.de/assets/img/post-img/2012/IMG_20121122_200631.jpg
und
https://www.netz39.de/assets/img/post-img/2014/3373_8a9e_500.gif

2024-11-10 15:14 UTC, penguineer approved these changes
nit: Nächstes Mal bitte einen  neuen Branch aufmachen!

2024-11-10 15:14 UTC, merged